spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/nmb_dev_db?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowLoadLocalInfile=true&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 400
      idle-timeout: 30000
      minimum-idle: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always